name: coding_test
description: "Coding Test - Robby Ramadhan"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.5
  get_it: ^8.0.3
  fluttertoast: ^8.2.2
  # google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
